name: Cypress Tests

# Controls when the workflow will run
on:
  # Triggers the workflow on push or pull request events but only for the "main" branch
  push:
    branches: ["develop"]
  pull_request:
    branches: ["develop"]

  # Allows you to run this workflow manually from the Actions tab
  workflow_dispatch:

jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - uses: actions/setup-node@v3
        with:
          node-version: 18.14
      - name: Install Netlify CLI
        run: npm install-g netlify-cli
      - name: Install dependencies
        run: npm install
      - name: Deploy
        run: npm run deploy
        env:
          NETLIFY_BUILD_DEVELOP: ${{ secrets.NETLIFY_BUILD_DEVELOP }}
          NETLIFY_SITE_ID: ${{ secrets.NETLIFY_SITE_ID }}
